apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gvn52ql7h-nodejs
  janus-idp.io/tekton: gvn52ql7h-nodejs
  backstage.io/kubernetes-id: gvn52ql7h-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gvn52ql7h-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
